config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # User management
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),

    path('', include('main.urls')),  # основной проект
    path('courses/', include('courses.urls')),  # курсы

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from .views import *

app_name = 'courses'

urlpatterns = [
    path('', index, name='main'),

    path('all/', all_courses, name='all'),
    path('follower/', follower_courses, name='follower'),
    path('create/', create_courses, name='create'),
]

main/urls.py
from django.urls import path
from .views import *
app_name = 'main'

urlpatterns = [
    path('', index, name='home' ),
]

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> <!-- Подключаем стили -->
    <title>{% block title %}Главная{% endblock title %}</title> <!-- Отображается в заголовке сайта --><!-- <h1></h1> Не обходи на кажой страници ()для поиска -->
    <meta name="description" content="Изучйте слова с легкостью "> <!-- для описания саайта в браузере -->

</head>
<body>

<nav><!-- Навгация -->
    <ul>
        {% block nav %}
        {% if user.is_authenticated %}
            <li><a href="#">Иконка приложения</a></li>
            <li><a href="{% url 'courses:main' %}">Курсы</a></li>
            <li><a href="#">Поиск</a></li>
            <li><a href="#">Пользователь</a></li>
        {% else %}
            <li><a href="{% url 'account_login' %}">Вход</a></li>
            <li><a href="{% url 'account_signup' %}">Регистация</a></li>
        {% endif %}
        {% endblock %}
    </ul>
</nav>

{% block content %}

{% endblock content %}

<!-- Блок для приложения django-allauth выводит вопрос об удалении email-->
    {% block extra_body %}
    {% endblock %}
<!-- ********************************** -->

    <footer> <!-- Подвал-->
        <nan></nan>
    </footer>

</body>
</html>