config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # User management
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),

    path('', include('main.urls')),  # основной проект
    path('courses/', include('courses.urls')),  # курсы

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from .views import *

app_name = 'courses'

urlpatterns = [
    path('', index, name='main'),

    path('all/', all_courses, name='all'),
    path('follower/', follower_courses, name='follower'),
    path('create/', create_courses, name='create'),
]

main/urls.py
from django.urls import path
from .views import *
app_name = 'main'

urlpatterns = [
    path('', index, name='home' ),
]

courses/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator


class Course(models.Model):
    """Модель курса"""
    CHOICE = (
        ('a', 'Легкий уровень'),
        ('b', 'Средний уровень'),
        ('c', 'Сложный уровень'),
    )
    level = models.CharField(choices=CHOICE, max_length=1, verbose_name='Уровень сложности')
    title = models.CharField(max_length=75, verbose_name='Название', db_index=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Автор')
    created = models.DateTimeField('Дата создания', auto_now_add=True)
    updated = models.DateTimeField('Дата последнего редактирования', auto_now=True)
    rating = models.IntegerField('Рейтинг', validators=[MinValueValidator(1), MaxValueValidator(5)], default=1)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "Курс"
        verbose_name_plural = "Курсы"
        ordering = ['-created']

courses/views.py
from django.shortcuts import render
from .servises import *
from .models import Course

sort_positions = {
    'рейтингу': 'rating',
    'авторам': 'author',
    'сложности': 'level',
    'дате создания': 'created',
}


def index(request):
    return render(request, 'courses/index.html', context={"object": "Главная страница курсов"})


def all_courses(request):

    if request.POST:
        fillters = request.POST.get('filtration')
        all_object_courses = fillter(
            object=Course.objects,
            filter=fillters
        )
    else:
        all_object_courses = all_object(object=Course.objects)

    context = {
        "title": "Список все курсы",
        'all_object_courses': all_object_courses,
        'sort_positions': sort_positions,

    }
    return render(request, 'courses/all_courses.html', context=context)


def follower_courses(request):
    return render(request, 'courses/follower_courses.html', context={"object": "Курсы на которые подписаны"})


def create_courses(request):
    return render(request, 'courses/create_courses.html', context={"object": "создание курсов"})

templates/courses/all_courses.html
<h1>{{ title }}</h1>

<h2>Сортировка по:</h2>


<form action="{% url 'courses:all' %}" method="POST">
    {% csrf_token %}
    {% for sort_rus_name, sort_eng_name  in sort_positions.items  %}
        <input type='checkbox' name="filtration" value="{{ sort_eng_name  }}">
         <span>{{ sort_rus_name }}</span>
    {% endfor %}
    <button type="submit">Сортировать</button>
</form>


{% for course in all_object_courses %}
    <p>
        <li>Название:{{ course }}</li>
        <li>Рейтинг:{{ course.rating }}</li>
        <li>Сложность:{{ course.get_level_display }}</li>
        <li>Автор:{{ course.author }}</li>
        <li>Дата создания:{{course.created}}</li>
    </p>
    <hr>
{% endfor %}



templates/courses/create_courses.html
<h1>{{ object }}</h1>

templates/courses/follower_courses.html
<h1>{{ object }}</h1>

templates/courses/index.html
<h1>Список сылок на курсы</h1>


<nav><!-- Навгация -->
    <ul>
        {% block nav %}
            <li><a href="{% url 'courses:all' %}">Все курсы</a></li>
            <li><a href="{% url 'courses:follower' %}">Курсы которые я учу</a></li>
            <li><a href="{% url 'courses:create' %}">Создать свой курс</a></li>
        {% endblock %}
    </ul>
</nav>